from datetime import datetime

from jsonfeed import JSONFeed

from util import logger

feed_filename = "posts.feed.json"


def generate_feed(posts: [dict]) -> JSONFeed:
    feed = JSONFeed(
        title="Recent mirror.xyz updates",
        link="https://github.com/arweave-tracker",
        description="Auto generated by arweave-tracker.",
        feed_url=f"https://raw.githubusercontent.com/RoCry/arweave-tracker/deploy/{feed_filename}",
        author_name="RoCry",
        author_link="https://github.com/RoCry",
    )
    for p in posts:
        feed.add_item(**_entry_to_feed_item(p))
    return feed


def _entry_to_feed_item(p: dict) -> dict:
    contributor = p["contributor"]
    digest = p["digest"]
    _id = p["id"]
    item = {
        "title": p["title"],
        "link": f"https://mirror.xyz/{contributor}/{digest}",
        "unique_id": f"arweave://{_id}",
        "description": p["body"],
        "author_name": contributor,
        "author_link": f"https://mirror.xyz/{contributor}",
        "pubdate": datetime.fromtimestamp(p["timestamp"]),
    }

    logger.debug(f"item: {item}")
    return item
